"""
Author: Hatim
Extracts the PC-Addresses from the file generated by
`print-functions.py`. Assumes that the format is:
	PC-Address Label Function-Name
"""

import sys

if len(sys.argv) != 3:
	print ("Usage: python3 extract-address.py benchmark ISA")
	sys.exit(1)

benchmark = sys.argv[1]
benchmark = benchmark.strip().lower()
ISA = sys.argv[2]
ISA = ISA.strip().lower()

input_file = f"../{ISA}-gem5/pc-address/{benchmark}.pc.txt"
output_file = f"../{ISA}-gem5/inputs/pc-address.txt"

with open(input_file, "r") as infile, open(output_file, "w") as outfile:
    for line in infile:
        words = line.strip()
        # print (words)
        address = words.split()[0]

        if ISA == "x86":
            print(address[-16:], file=outfile)
        else: # ISA == "arm"
            print(address[-8:], file=outfile)
